name: Call Dev Tag Workflow

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  call-dev-tag:
    uses: ./.github/workflows/dev-tag-reusable.yml
    with:
      tag_suffix: "tcg-dev"
