name: Deploy to AWS Asia

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy resources'
        required: true
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Auto Tag Commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          ### TAG="v$(date +'%Y%m%d%H%M%S')"
          TAG="v$(date +'%Y%m%d')-1-tcg-dev"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag "$TAG"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin "$TAG"

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CN }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-south-1

      - name: Create S3 bucket
        run: |
          BUCKET_NAME="statefilebackup202512"
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Change directory
        run: cd vpc-flow-logs

      - name: Terraform Init
        run: terraform init
        working-directory: vpc-flow-logs

      - name: Terraform Plan
        run: terraform plan
        working-directory: vpc-flow-logs

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: vpc-flow-logs

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve
        working-directory: vpc-flow-logs

      - name: Empty and delete S3 bucket
        if: github.event.inputs.destroy == 'true'
        run: |
          BUCKET_NAME="flow-logs-bucketvpc07457e1-cn-northwest-1"
          aws s3 rm s3://$BUCKET_NAME --recursive
          aws s3api list-object-versions --bucket "$BUCKET_NAME" --query 'Versions[].{Key:Key,VersionId:VersionId}' --output text | while read key version; do
            aws s3api delete-object --bucket "$BUCKET_NAME" --key "$key" --version-id "$version"
          done
          aws s3api list-multipart-uploads --bucket "$BUCKET_NAME" --query 'Uploads[].{Key:Key,UploadId:UploadId}' --output text | while read key upload_id; do
            aws s3api abort-multipart-upload --bucket "$BUCKET_NAME" --key "$key" --upload-id "$upload_id"
          done
          aws s3api delete-bucket --bucket "$BUCKET_NAME" --region cn-northwest-1
