name: Deploy to AWS Asia

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy resources'
        required: true
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS CLI for the appropriate region
      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CN }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-south-1

      # Create S3 bucket if it doesn't exist
      - name: Create S3 bucket
        run: |
          BUCKET_NAME="statefilebackup202512"
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1
          fi

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      # Change directory to where main.tf is located
      - name: Change directory
        run: cd vpc-flow-logs

      # Initialize Terraform with S3 backend
      - name: Terraform Init
        run: terraform init
        working-directory: vpc-flow-logs

      - name: Terraform Plan
        run: terraform plan
        working-directory: vpc-flow-logs

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: vpc-flow-logs

      # Destroy Terraform resources
      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve
        working-directory: vpc-flow-logs
