name: Deploy to AWS Asia

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy resources'
        required: true
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS CLI for the appropriate region
      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-south-1

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      # Change directory to where main.tf is located
      - name: Change directory
        run: cd vpc-flow-logs

      # Initialize Terraform with S3 backend
      - name: Terraform Init
        run: |
          terraform init -backend-config="statefilebackup202512" \
                         -backend-config="statefile/terraform.tfstate" \
                         -backend-config="region=ap-south-1" 
                         #-backend-config="dynamodb_table=your-lock-table"
        working-directory: vpc-flow-logs

      - name: Terraform Plan
        run: terraform plan
        working-directory: vpc-flow-logs

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: vpc-flow-logs

      # Destroy Terraform resources
      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve
        working-directory: vpc-flow-logs
