# .github/workflows/tag-and-release.yml

name: Tag MultiEnv

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, uat, prod)'
        required: true
        default: 'dev'

permissions:
  contents: write

jobs:
  tag:
    uses: ./.github/workflows/tag-reusable.yml
    with:
      tag_suffix: tcg-${{ github.event.inputs.environment }}

  release:
    needs: tag
    uses: ./.github/workflows/release-auto.yml
    with:
      tag_name: ${{ needs.tag.outputs.tag_name }}
